Add fix for trellis commands failure
triggerfishab/lisa-cli pull request #5
Opened 2022-08-10 06:56 UTC by phpanos

Run trellis init command before running trellis dotenv when cloning an existing project.

2022-08-10 07:09 UTC, moelleer approved these changes

2022-08-10 07:09 UTC, moelleer requested changes
Please add the changes to the changelog aswell.

2022-08-10 07:35 UTC, moelleer requested changes

2022-08-10 07:35 UTC, moelleer commented on CHANGELOG.md
> +## 2.2.2 (2022-08-10)
This should be named unreleased without a date until it is released.

2022-08-10 07:35 UTC, tf-tomas commented
Keep up the good work mate!

2022-09-23 11:33 UTC, moelleer approved these changes

2022-09-23 11:33 UTC, merged