Feature/aws iam user
triggerfishab/lisa-cli pull request #52
Opened 2023-09-28 11:45 UTC by lissmeister

2023-09-28 11:58 UTC, chrillep requested changes

2023-09-28 11:58 UTC, chrillep commented on tasks/services/aws.js
> +              Expiration: { ExpiredObjectDeleteMarker: true },
30 dagar ?

2023-10-03 11:03 UTC, lissmeister commented on tasks/services/aws.js
> +              Expiration: { ExpiredObjectDeleteMarker: true },
Är som det ska va

2023-10-10 16:28 UTC, chrillep commented
Woop Woop

2023-10-10 16:29 UTC, chrillep approved these changes
Woop woop

2023-10-11 07:50 UTC, merged